FROM swr.cn-north-12.myhuaweicloud.com/base_image/ascend-ci/cann:9.1.0-a3-ubuntu22.04-py3.12

ARG PIP_INDEX_URL
ARG COMPILE_CUSTOM_KERNELS

LABEL device="a3" os="ubuntu"

CMD ["echo", "hello from a3/ubuntu"]
