/** SPDX-License-Identifier: Apache-2.0 */
#ifndef TEMPLATE_TILING_KEY_GLMKPOOL_SPLIT_AIC_H_
#define TEMPLATE_TILING_KEY_GLMKPOOL_SPLIT_AIC_H_
#include "ascendc/host_api/tiling/template_argument.h"
#define GLMK_SPLIT_AIC_FP16 1
#define GLMK_SPLIT_AIC_BF16 27
ASCENDC_TPL_ARGS_DECL(Glm5KpoolSplitAic,
                      ASCENDC_TPL_DTYPE_DECL(DT_Q, GLMK_SPLIT_AIC_FP16, GLMK_SPLIT_AIC_BF16), );
ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DTYPE_SEL(DT_Q, GLMK_SPLIT_AIC_FP16), ),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_DTYPE_SEL(DT_Q, GLMK_SPLIT_AIC_BF16), ), );
#endif
